enable: "etcd"
etcd:
  rootDirectory: openim
  address: [ 127.0.0.1:12379 ]
  username: ''
  password: ''

kubernetes:
  namespace: default

rpcService:
  chat: chat-rpc-service
  admin: admin-rpc-service
  bot: bot-rpc-service
